Description: Template to create Sagemaker Notebook for advanced DeepRacer training
Resources:
  DeepHacksRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
                - robomaker.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Role for DeepHacks
      RoleName: DeepHacksRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonKinesisVideoStreamsFullAccess
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/AmazonElasticContainerRegistryPublicReadOnly
        - arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilderECRContainerBuilds
        - arn:aws:iam::aws:policy/service-role/AWSDeepRacerServiceRolePolicy
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'iam:PassRole'
                Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/DeepHacksRole'
              - Effect: Allow
                Action:
                  - 'ecr:DeleteRepository'
                Resource:
                  - !Sub 'arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/sagemaker-docker-cpu'
                  - !Sub 'arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/deepracer-sim-local-notebook'
          PolicyName: DeepHacksInlinePolicy
      MaxSessionDuration: 43200

  DPR401Notebook:
    Type: AWS::SageMaker::NotebookInstance
    Properties: 
      PlatformIdentifier: notebook-al2-v1
      DefaultCodeRepository: https://github.com/jeremypedersen/deepracer-deephacks.git
      DirectInternetAccess: Enabled
      InstanceType: ml.t3.large
      NotebookInstanceName: DeepHacks-Notebook
      RoleArn: !GetAtt DeepHacksRole.Arn
      RootAccess: Enabled
      VolumeSizeInGB: 30

